version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    restart: 'always'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host
    volumes:
      # You will need to create the path and permissions on the local file system where Elasticsearch will store data.
      # For example...
      #   mkdir /var/lib/128t-monitoring-es && chown -R 1000:1000 /var/lib/128t-monitoring-es
      - /var/lib/128t-monitoring-es:/usr/share/elasticsearch/data
    environment:
      cluster.name: '128t-metrics'
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'
      bootstrap.memory_lock: 'true'
      network.host: 0.0.0.0
      http.port: 9200
      discovery.type: 'single-node'
      indices.query.bool.max_clause_count: 8192
      search.max_buckets: 100000
      action.destructive_requires_name: 'true'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    restart: 'always'
    network_mode: host
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601
      SERVER_MAXPAYLOADBYTES: 4194304
      ELASTICSEARCH_HOSTS: "http://127.0.0.1:9200"
      LOGGING_DEST: stdout
      LOGGING_QUIET: 'false'
      KIBANA_DEFAULTAPPID: 'dashboard/756c8150-8a30-11ea-9144-6b2f8df985d5'

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.6.3
    volumes:
      - ./zookeeper/data:/data
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 117.184.114.143
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
    volumes:
      - ./kafka:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    container_name: kafka-logstash
    network_mode: host
    volumes:
      - "./kafka-logstash:/usr/share/logstash/pipeline"
